# docker-compose.yml
version: '3.11'

services:
  web:
    build: ./web-app
    ports:
      - "5001:5001"
    volumes:
      - ./web-app:/app
      - shared_data:/app/data
      - ./common:/app/common 
    environment:
      - PYTHONPATH=/app:/app/common
      - MONGO_URI=${MONGO_URI}
      - LLM_SERVICE_URL=http://llm:5002
    depends_on:
      mongodb:
        condition: service_healthy
      llm:
        condition: service_started
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]

  llm:
    build: ./llm
    ports:
      - "5002:5002"
    volumes:
      - ./llm:/app
      - shared_data:/app/data
      - ./common:/app/common 
    environment:
      - PYTHONPATH=/app:/app/common
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_PROVIDER=${API_PROVIDER}
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["uvicorn", "llm_app:app", "--host", "0.0.0.0", "--port", "5002", "--reload"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  shared_data: