# docker-compose.yml
version: '3.8'

services:
  web:
    build: ./web-app
    ports:
      - "5001:5001"
    volumes:
      - shared_data:/app/data
      - ./common:/app/common
    environment:
      - PYTHONPATH=/app:/app/common
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - ML_SERVICE_URL=http://ml:5002
    depends_on:
      mongodb:
        condition: service_healthy
      ml:
        condition: service_started

  ml:
    build: ./ml
    ports:
      - "5002:5002"
    volumes:
      - shared_data:/app/data
      - ./common:/app/common
    environment:
      - PYTHONPATH=/app:/app/common
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  shared_data: