# pytest settings that might help... feel free to modify or remove as needed

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --cov=./ --cov-report=term-missing"
pythonpath = ["."]
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    "error",  # Turn warnings into errors
    "ignore::pytest.PytestDeprecationWarning"  # Specifically ignore the asyncio warning
]