name: common CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'common/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'common/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r common/requirements.txt
      
      - name: Setup environment variables
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/test_db" >> $GITHUB_ENV

      - name: Run common tests with coverage
        run: |
          python -m pytest common/tests --cov=common -v 