name: llm CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'llm/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'llm/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r llm/requirements.txt
          pip install -r common/requirements.txt
      
      - name: Setup test environment variables
        run: |
          echo "LLM_API_PROVIDER=GEMINI" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=fake_key_for_testing" >> $GITHUB_ENV
      
      - name: Run tests
        run: |
          python -m pytest llm/tests --cov=llm -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (CI only)
        uses: docker/build-push-action@v3
        with:
          context: ./llm
          file: ./llm/Dockerfile
          push: false

  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push llm
        uses: docker/build-push-action@v3
        with:
          context: ./llm
          file: ./llm/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/stock-llm:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/stock-llm:${{ github.sha }}

