name: web-app CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'web-app/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
          
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r web-app/requirements.txt
          pip install -r common/requirements.txt
      
      - name: Create template files for tests
        run: |
          mkdir -p web-app/templates
          touch web-app/templates/index.html
          touch web-app/templates/detail.html
          touch web-app/templates/trending.html
          
      - name: Setup test environment variables
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/test_db" >> $GITHUB_ENV
          
      - name: Run tests
        run: |
          python -m pytest web-app/tests --cov=web-app -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (CI only)
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: false

  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push web-app
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/stock-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/stock-web:${{ github.sha }}
